# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm>=8.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "its_hub"
description = "A Python library for inference-time scaling LLMs"
authors = [
    {name = "Kai Xu and the Red Hat AI Innovation Team", email = "xuk@redhat.com"}
]
readme = "README.md"
requires-python = ">=3.11"
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dynamic = ["version"]
dependencies = [
    "openai>=1.75.0",
    "tqdm>=4.65.0",
    "typing-extensions>=4.0.0",
    "reward-hub==0.1.1",
    "vllm<=0.9.1",  # Pin to avoid build issues with newer versions requiring Rust compilation
    "backoff>=2.2.0",
    "click>=8.1.0",
    "fastapi>=0.115.0",
    "uvicorn>=0.34.0",
    "pydantic>=2.11.0",
    "numpy>=1.24.0",
    "requests>=2.28.0",
    "aiohttp>=3.8.0"
]

[project.scripts]
its-iaas = "its_hub.integration.iaas:main"

[tool.setuptools_scm]
version_file = "its_hub/_version.py"
# do not include +gREV local version, required for Test PyPI upload
local_scheme = "no-local-version"

[project.urls]
Homepage = "https://ai-innovation.team/its_hub"

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.1.0",
    "ruff>=0.8.0",
    "jupytext>=1.15.0",
    "jupyter>=1.0.0",
]

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = [
    "its_hub",
    "its_hub.algorithms",
    "its_hub.integration",
]

